# Generated by Django 5.2.7 on 2025-10-30 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='menu.category', verbose_name='부모 카테고리')),
            ],
            options={
                'verbose_name': '메뉴 카테고리',
                'verbose_name_plural': '메뉴 카테고리',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='가격')),
                ('description', models.TextField(verbose_name='메뉴 설명')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='기타 사항')),
                ('describe_image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='메뉴 이미지')),
                ('is_available', models.BooleanField(default=True, verbose_name='판매 가능 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menu.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '메뉴 항목',
                'verbose_name_plural': '메뉴 항목',
                'ordering': ['name'],
            },
        ),
    ]
