# Generated by Django 5.2.7 on 2025-11-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='describe_image',
        ),
    ]
