# Generated by Django 5.2.7 on 2025-11-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menuitem_describe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='카테고리 이미지'),
        ),
        migrations.AddField(
            model_name='category',
            name='display_type',
            field=models.CharField(choices=[('text', '텍스트'), ('image', '이미지')], default='text', max_length=10, verbose_name='표시 방식'),
        ),
    ]
