# Generated by Django 5.2.7 on 2025-11-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_category_image_category_display_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='display_type',
        ),
    ]
