# Generated by Django 5.2.7 on 2025-11-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_category_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='메뉴 이미지'),
        ),
    ]
