# Generated by Django 5.2.7 on 2025-11-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['priority', 'name'], 'verbose_name': '메뉴 항목', 'verbose_name_plural': '메뉴 항목'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='priority',
            field=models.IntegerField(default=0, help_text='낮은 숫자일수록 먼저 표시됩니다', verbose_name='우선순위'),
        ),
    ]
