# Generated by Django 5.2.7 on 2025-11-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menuitem_options_menuitem_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority', 'name'], 'verbose_name': '메뉴 카테고리', 'verbose_name_plural': '메뉴 카테고리'},
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=0, help_text='낮은 숫자일수록 먼저 표시됩니다', verbose_name='우선순위'),
        ),
    ]
