# Generated by Django 5.2.7 on 2025-11-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_category_options_category_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='intro_video',
            field=models.FileField(blank=True, help_text='로딩 화면에 표시될 인트로 비디오 (MP4 파일)', null=True, upload_to='site_videos/', verbose_name='인트로 비디오'),
        ),
    ]
