# Generated by Django 5.2.7 on 2025-11-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_sitesettings_intro_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='카테고리 이미지'),
        ),
    ]
