# Generated by Django 5.2.7 on 2025-11-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='메뉴명(영문)'),
        ),
    ]
