# Generated by Django 5.2.7 on 2025-11-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menuitem_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_description_font',
            field=models.CharField(blank=True, help_text="예: 'Noto Sans KR', Arial, sans-serif", max_length=100, null=True, verbose_name='메뉴 설명 폰트'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_name_en_font',
            field=models.CharField(blank=True, help_text="예: 'Roboto', Arial, sans-serif", max_length=100, null=True, verbose_name='메뉴명(영문) 폰트'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_name_font',
            field=models.CharField(blank=True, help_text="예: 'Noto Sans KR', Arial, sans-serif", max_length=100, null=True, verbose_name='메뉴명(한글) 폰트'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_price_font',
            field=models.CharField(blank=True, help_text="예: 'Roboto', Arial, sans-serif", max_length=100, null=True, verbose_name='가격 폰트'),
        ),
    ]
