# Generated by Django 5.2.7 on 2025-11-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_sitesettings_menu_description_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_description_color',
            field=models.CharField(blank=True, default='', help_text='#aaaaaa', max_length=7, verbose_name='메뉴 설명 색상'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_name_color',
            field=models.CharField(blank=True, default='', help_text='#ffffff', max_length=7, verbose_name='메뉴명(한글) 색상'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_name_en_color',
            field=models.CharField(blank=True, default='', help_text='#cccccc', max_length=7, verbose_name='메뉴명(영문) 색상'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_price_color',
            field=models.CharField(blank=True, default='', help_text='#ffffff', max_length=7, verbose_name='가격 색상'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_description_font',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='메뉴 설명 폰트'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_name_en_font',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='메뉴명(영문) 폰트'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_name_font',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='메뉴명(한글) 폰트'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_price_font',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='가격 폰트'),
        ),
    ]
