# Generated by Django 5.2.7 on 2025-11-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_sitesettings_menu_description_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_description_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='메뉴 설명 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_name_en_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='메뉴명(영문) 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_name_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='메뉴명(한글) 폰트 파일'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='menu_price_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='가격 폰트 파일'),
        ),
    ]
