# Generated by Django 5.2.7 on 2025-11-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_sitesettings_menu_description_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='side_image',
            field=models.ImageField(blank=True, help_text='사이드 메뉴 등에 사용될 이미지', null=True, upload_to='site_images/', verbose_name='사이드 이미지'),
        ),
    ]
