# Generated by Django 5.2.7 on 2025-11-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_sitesettings_side_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_description_size',
            field=models.IntegerField(blank=True, help_text='픽셀 단위 (예: 14)', null=True, verbose_name='메뉴 설명 크기'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_name_en_size',
            field=models.IntegerField(blank=True, help_text='픽셀 단위 (예: 14)', null=True, verbose_name='메뉴명(영문) 크기'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_name_size',
            field=models.IntegerField(blank=True, help_text='픽셀 단위 (예: 18)', null=True, verbose_name='메뉴명(한글) 크기'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_price_size',
            field=models.IntegerField(blank=True, help_text='픽셀 단위 (예: 20)', null=True, verbose_name='가격 크기'),
        ),
    ]
