# Generated by Django 5.2.7 on 2025-11-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_sitesettings_menu_description_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_description_bold',
            field=models.BooleanField(default=False, verbose_name='메뉴 설명 볼드'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_description_italic',
            field=models.BooleanField(default=False, verbose_name='메뉴 설명 이탤릭'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_name_bold',
            field=models.BooleanField(default=False, verbose_name='메뉴명(한글) 볼드'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_name_en_bold',
            field=models.BooleanField(default=False, verbose_name='메뉴명(영문) 볼드'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_name_en_italic',
            field=models.BooleanField(default=False, verbose_name='메뉴명(영문) 이탤릭'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_name_italic',
            field=models.BooleanField(default=False, verbose_name='메뉴명(한글) 이탤릭'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_price_bold',
            field=models.BooleanField(default=False, verbose_name='가격 볼드'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_price_italic',
            field=models.BooleanField(default=False, verbose_name='가격 이탤릭'),
        ),
    ]
