# Generated by Django 5.2.7 on 2025-12-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_sitesettings_menu_description_bold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hide_side_image',
            field=models.BooleanField(default=False, help_text='체크하면 이 카테고리에서 배경 이미지가 뒤로 숨겨집니다', verbose_name='사이드 이미지 숨기기'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리명(영문)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_name_bold',
            field=models.BooleanField(default=False, verbose_name='카테고리명(한글) 볼드'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_name_color',
            field=models.CharField(blank=True, default='', help_text='#ffffff', max_length=7, verbose_name='카테고리명(한글) 색상'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_name_en_bold',
            field=models.BooleanField(default=False, verbose_name='카테고리명(영문) 볼드'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_name_en_color',
            field=models.CharField(blank=True, default='', help_text='#cccccc', max_length=7, verbose_name='카테고리명(영문) 색상'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_name_en_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='카테고리명(영문) 폰트 파일'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_name_en_italic',
            field=models.BooleanField(default=False, verbose_name='카테고리명(영문) 이탤릭'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_name_en_size',
            field=models.IntegerField(blank=True, help_text='픽셀 단위 (예: 14)', null=True, verbose_name='카테고리명(영문) 크기'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_name_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='카테고리명(한글) 폰트 파일'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_name_italic',
            field=models.BooleanField(default=False, verbose_name='카테고리명(한글) 이탤릭'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='category_name_size',
            field=models.IntegerField(blank=True, help_text='픽셀 단위 (예: 18)', null=True, verbose_name='카테고리명(한글) 크기'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='카테고리명(한글)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.CharField(help_text='가격을 입력하세요 (예: 15000, 15.5, 15,000)', max_length=50, verbose_name='가격'),
        ),
    ]
