# Generated by Django 5.2.7 on 2026-01-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_category_hide_side_image_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_notes_bold',
            field=models.BooleanField(default=False, verbose_name='기타 사항 볼드'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_notes_color',
            field=models.CharField(blank=True, default='', help_text='#888888', max_length=7, verbose_name='기타 사항 색상'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_notes_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/', verbose_name='기타 사항 폰트 파일'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_notes_italic',
            field=models.BooleanField(default=False, verbose_name='기타 사항 이탤릭'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_notes_size',
            field=models.IntegerField(blank=True, help_text='픽셀 단위 (예: 12)', null=True, verbose_name='기타 사항 크기'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='카테고리명(한글)'),
        ),
    ]
