# Generated by Django 5.2.7 on 2026-01-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_sitesettings_menu_notes_bold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.FloatField(default=0.0, help_text='낮은 숫자일수록 먼저 표시됩니다', verbose_name='우선순위'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='priority',
            field=models.FloatField(default=0.0, help_text='낮은 숫자일수록 먼저 표시됩니다', verbose_name='우선순위'),
        ),
    ]
