# Generated by Django 5.2.7 on 2026-01-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_alter_category_priority_alter_menuitem_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.TextField(help_text='가격을 입력하세요 (예: 15000, 15.5, 15,000)', verbose_name='가격'),
        ),
    ]
